import React from "react";
import Menu from "./components/Menu"; 
import { UserProvider } from "./context/UserContext";
import "./globals.css";


export const metadata = {
  title: "My Next.js App",
  description: "Generated by Next.js",
};


interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  
  return (
    <html lang="pt-BR">
      
      <body>
        <UserProvider>
          <Menu />
          {children}
        </UserProvider>
      </body>
    </html>
  );
};

export default RootLayout;
